HobbyHub-1/HobbyHub

README.md
=> HH-20 #comment 연습 연습

accounts/models.py, config/settings.py, posts/models.py, requirements.txt
- HH-?? #comment feat : models.py 작성
- Add accounts/models.py : User, Question, Response, Recommendation
- Add posts/models.py : Post, Post_Comment, Group, Group_Comment
- Add settings.py : taggit 모듈 설치
- requirements.txt 설치하세요
=> HH-?? #comment feat : models.py 작성

config/urls.py, posts/forms.py, posts/templates/index.html, posts/templates/posts/index.html, posts/templates/posts/post_create.html, posts/templates/posts/post_detail.html, posts/templates/posts/post_update.html, posts/urls.py, posts/views.py, templates/base.html
- posts/index, 게시물CRUD, 댓글 기본 구현, 좋아요
- posts 앱 
- Add : index, post_create, post_detail, post_update.html 기본 CRUD 템플릿 생성
- Update : urls.py, views.py 게시글과 댓글 작성, 게시글에 대한 좋아요 비동기 구현 
(프론트엔드 레이아웃은 미완성 상태)
- Add : forms.py 정보입력을 위한 최소한의 기본 구현 
- Update : templates/base.html
- accounts와 posts 각각 models.py이 미완성이라 index쪽 로그인/회원가입 버튼 주석처리 되어 있음
=> HH-23 HH-24 HH-25 HH-34 #Start #comment feat : index posts 게시물 댓글 기본 구현

accounts/models.py, posts/models.py
- HH-26 #commen feat : posts/models.py class Group 수정
- update : posts/models.py 수정
- location 활용 방안 논의
-
=> HH-26 #comment feat : posts/models.py class Group 수정

posts/templates/posts/index.html, static/css/index.css, static/js/index.js, templates/base.html
- card 템플릿 추가
- Add : static/index.css card 템플릿용 style.css 추가
- Update : index.html card 템플릿 샘플 생성성
- 샘플용 card로 모바일과 PC용에 둘다 사용될 예정입니다.
=> HH-35 #comment feat : index 페이지 card 템플릿 추가

accounts/forms.py, accounts/templates/login.html, accounts/templates/signup.html, accounts/urls.py, accounts/views.py
-login, signup 기능 추가 
--accounts앱 views.py, urls.py, forms.py 일부 작성
-login.html, signup.html(CSS 없음) 완성
-
=> HH-27, HH-33 #comment feat login, signup 기능 추가 

posts/forms.py, posts/models.py, posts/urls.py, posts/views.py
- HH-32 #comments feat : posts/urls, views 
- Add : posts group urls 작성
- Update : posts/models,  , views , forms 수정 및 class 추가 작성
-
=> HH-32 #comments feat : posts/urls, views 작성

posts/forms.py, posts/models.py, posts/templates/posts/post_create.html, posts/templates/posts/post_detail.html, posts/urls.py, posts/views.py
- develop 오류 수정
- posts/templates, models, forms, urls, views 버그수정
- image 출력 오류
=> HH-37 #comment fix : develop 오류 수정

accounts/forms.py, accounts/models.py, accounts/templates/login.html, accounts/templates/signup.html, accounts/urls.py, accounts/views.py, config/settings.py, config/urls.py, posts/forms.py, posts/models.py, posts/templates/index.html, posts/templates/posts/index.html, posts/templates/posts/post_create.html, posts/templates/posts/post_detail.html, posts/templates/posts/post_update.html, posts/urls.py, posts/views.py, requirements.txt, static/css/index.css, static/js/index.js, templates/base.html
- 5월 26일 (금) develop 개발 상황 업로드 
- models 생성
- accoutns/로그인, 회원가입 기본구현
- posts/게시물과 댓글 CRUD, 게시물 likes 비동기, 
-
=> 4차 병합 : develop -> main

accounts/models.py, config/urls.py, posts/templates/posts/post_detail.html
-  accounts, posts image 출력 오류수정
- fix : accounts/models 수정
- fix : posts/templates/posts/post_detail.html 수정
- update : config/urls media 루트 추가
-
=> HH-38 #comment fix : accounts, posts image 출력 오류수정

posts/forms.py, posts/models.py, posts/templates/posts/group_create.html, posts/templates/posts/group_detail.html, posts/templates/posts/group_list.html, posts/templates/posts/group_update.html, posts/templates/posts/post_detail.html, posts/templates/posts/post_update.html, posts/urls.py, posts/views.py
-  group crud 기능 추가
- Add : posts/views.py group crud 작성
- Add : group crud 해당 templates 작성
- fix : posts/post_update.html 오타 수정
-
=> HH-39 #comment feat : group crud 기능 추가

accounts/forms.py, accounts/templates/accounts/login.html, accounts/templates/accounts/signup.html, accounts/templates/accounts/test.html, accounts/templates/accounts/update.html, accounts/urls.py, accounts/views.py
- logout, profile, profile update 추가
- logout, profile, profile update를 위한 views, urls, forms 변경 및 템플릿 추가
- profile.html은 순수 html로 레이아웃을 보기 위한 목적으로 테스트 페이지에 연결함. 추후 수정 필요
- CSS 없이 순수 form이 다수. 프론트적으로 손을 봐야 함.
- 비밀번호 변경 페이지는 오류가 확인되어 커밋 전. 리퀘스트한 내용은 정상작동함
=> HH-36 #comment feat : logout, profile, profile update 추가

posts/forms.py, posts/models.py, posts/templates/posts/category.html, posts/templates/posts/group_detail.html, posts/templates/posts/index.html, posts/templates/posts/post_detail.html, posts/templates/posts/search.html, posts/urls.py, posts/views.py, static/js/group_detail.js
- group comment,  group like, search, category 기능 구현
- Update : posts/models Post, Group 모델 수정
- Add : posts/views group comment 조회, 생성, 삭제 뷰함수와 group_detail에 comment 기능 추가
- Add : posts/views group likes 뷰함수 및 js 작성
- Add : posts/views search, category 뷰함수 및 템플릿 작성
-
=> HH-41, 43, 44 #comment feat : group comment,  group like, search, category 기능 구현

static/css/navbar.css, templates/base.html, templates/navbar.html
- navbar 구현중
- Update : templates/base.html, navbar.html
- Add : staic/css/navbar.css
- 아직 미완성입니다. 좀 더 수정할 예정입니다.
=> HH-28 HH-47 #comment feat : navbar 구현중

templates/base.html
- logo 이미지 오류 해결
- base 템플릿에 삽입한 이미지 파일이 깃허브 상으로 저장되지 않아 발생한 오류입니다.
- 해당 이미지 부분 주석처리하였습니다.
-
=> logo 오류 해결

posts/templates/posts/index.html, static/css/index.css, static/css/index_carousel.css, static/js/carousel.js, templates/base.html
- index.html 캐로젤 구현
- Updtae : posts/index.html, static/index.css
- Add : static/carousel.css, carousel.js
-
=> HH-40 #comment feat : index carousel 구현

accounts/templates/accounts/profile.html, accounts/templates/accounts/update.html, accounts/urls.py, accounts/views.py
-버그수정
-팔로우, 언팔로우 기능 추가
-update.html에서 파일 수정할 경우 반영이 안 되는 부분 수정
-password.html에서 type error 나는 부분 수정
-예상했던 것과 진행방향이 좀 달랐음
-
=> HH-?? #comment fix : profile.html 수정

posts/forms.py, posts/urls.py, posts/views.py, static/js/index.js, static/js/index_tags_filter.js
- 취미 필터링 기능 추가
- Update : posts/views.py index 뷰함수 수정
- Update : static/js/index 좋아요 태그 필터 병합
- Add : posts/index.html 태그 버튼 생성
- Add : static/js/index_tags_filter 태그에 따른 게시물 비동기 처리
- 아직 좋아요와 태그 필터링 비동기 js 코드를 합치는 중 입니다
=> HH-53 #comment feat : 취미 필터링 기능 추가

posts/views.py
- 필터링과 좋아요 버튼 JS 기능 병합
- Update : posts/index.html div 태그수정, 카드형식으로 변경
- Update : posts/views.py index, post_delete, post_update 뷰함수 수정
- index.html 과 js 는 신혜님이 쪽에서 커밋하기로 했습니다
=> HH-57 #comment feat : 필터링과 좋아요 버튼 JS 기능 병합

accounts/models.py, accounts/templates/accounts/profile.html, accounts/templates/accounts/update.html, accounts/views.py, static/js/profile.js
-버그픽스, 레이아웃 수정, 팔로우, 팔로잉 비동기 접근
- 파일 업로드가 반영되지 않는 버그 수정
- profile.html에 오른쪽 필드 틀 잡음
- 팔로잉 비동기 접근..을 시도했으나 아직 진행중
-
=> HH-59 #comment fix : 프로필 페이지 틀 잡음

posts/templates/posts/index.html, posts/templates/posts/post_detail.html, static/css/index.css, static/js/index.js
- index.html 
- card 좋아요 비동기
- 모바일 환경을 위한 레이아웃 grid 작업 진행
- Update : static/index.css, index.js
-
=> HH-?? #comment feat : index layout ongoing

posts/forms.py, posts/models.py, posts/templates/posts/group_create.html
- posts/models.py, forms.py 수정
- posts/models.py : 필터링 기능을 위한 models 추가 (day, region, gender, propensity, category 추가)
- posts/forms.py : models에 맞게 forms.py 추가
-
=> HH-61 #comment feat : posts/models.py, forms.py 수정

posts/templates/posts/index.html, posts/templates/posts/post_detail.html, static/css/carousel.css, static/css/index.css, static/css/index_carousel.css, static/css/post_detail.css, static/js/index.js
- index, post_detail 기초 레이아웃
- Update : index.html, post_detail.html
- Update : static/index, carousel, post_detail.css, post_detail.css
- Update : static/index, carousel.js
- index와 post_detail 화면의 케로젤을 함께 수정했고 커밋은 분리했습니다.
=> HH-60 HH-49 #comment feat : index, post_detail 기초 레이아웃

accounts/templates/accounts/profile.html, accounts/views.py, static/js/profile.js
- 프로필 페이지 완성도 높이기
- 다른 유저 프로필 방문했을 때 팔로우/언팔로우 관련 비동기 완성
- 전체적인 레이아웃 정리
-
=> HH-63 #comment fix : profile.html

posts/forms.py, posts/templates/posts/group_create.html, posts/templates/posts/where.html, posts/views.py
- group_create로 소모임 추가하면 위치에 따라 where.html에 마커 생성
- group_create.html : group_create 하면 form 형태로 db에 저장
- where.html : group_create 하면 지도에 마커 생성
- forms.py : group_create에 맞게 form 수정
- views.py : get_group_data() 작성
-
=> HH-54 #comment feat : group_create로 소모임 추가하면 위치에 따라 where.html에 마커 생성

accounts/templates/accounts/profile.html, accounts/views.py, posts/forms.py, posts/models.py, posts/templates/posts/group_create.html, posts/templates/posts/index.html, posts/templates/posts/post_detail.html, posts/templates/posts/where.html, posts/views.py, static/css/base.css, static/css/carousel.css, static/css/footer.css, static/css/index.css, static/css/navbar.css, static/css/post_detail.css, static/css/subdivision.css, static/js/index.js, static/js/profile.js, templates/base.html, templates/footer.html, templates/navbar.html, templates/subdivision.html
6월 2일 (금) 개발 현황 병합
- 태그 필터링
- 지도 마크 생성
- index, detail 레이아웃 
- profile
- navbar
=> 7차 병합 : develop -> main

posts/forms.py, posts/models.py, posts/templates/posts/group_list.html, posts/views.py, static/css/group_list.css
- group filter 기능 추가
- Update : posts/models.py 필터 검색 조건 추가
- Update : posts/forms.py 모델에 조건 추가에 따른 양식 추가
- Update : posts/views.py group_list 뷰함수에 필터검색 기능 추가
- Update : posts/templates/posts/group_list.html 템플릿에 필터 검색 기능 추가
- Add : static/css/group_list.css group_list 템플릿 css파일 작성
-
=> HH-58 #comment feat : group filter 기능 추가

posts/templates/posts/index.html, static/css/index.css, static/js/index.js
- index 비동기 오류 해결
- Update : index.heml,css,js
- 어제와 주말동안 커밋한 내용 사라져서 다시 했습니다.
=> HH-64 #comment feat : index 비동기 오류 수정

accounts/templates/accounts/profile.html
-충돌이 예상되어서 머지하고 리퀘스트함
-login 템플릿 충돌 수정 후 병합
-css 진행중
-소셜로그인 추가
-
=> HH-?? #comment login.html merge

posts/templates/posts/index.html
- index.html 누락 오류 해결
- 임시로 제가 보유하고 있던 인덱스 파일을 추가하여 머지합니다.
- index 쪽 수정이 여러 곳에서 일어나 발생한 문제로 여겨집니다.
=> index.html error

posts/templates/posts/where.html
- where.html에서 필터링 기능 추가하여 필터링에 따라 소모임 출력
- 필터링 드롭다운으로 구현하여 비동기로 마커 실시간 수정 완료
- 드롭다운에서 항목 선택 후 다시 all 선택하면 동작하지 않는 오류 있어서 평일에 다시 확인해야 할듯.
=> HH-55 #comment feat : where.html에서 필터링 기능 추가하여 필터링에 따라 소모임 출력

accounts/forms.py, accounts/templates/accounts/signup.html, static/css/signup.css
=> HH-?? #style signup.html

accounts/forms.py
-fix error
-회원가입 로직이 정상적으로 작동하지 않아 수정
-
=> HH-?? #fix forms.py

posts/templates/posts/category.html, posts/templates/posts/post_detail.html, posts/views.py, static/css/category.css
- category.html 레이아웃 구성 중간 커밋
- Update : posts/templates/posts/category.html 레이아웃 구성
- Update : posts/templates/posts/post_detail.html 태그 출력 코드 수정
- Update : posts/views.py category 뷰함수 수정
- Add : static/css/category.css
-
=> HH-?? #comment feat : category.html 레이아웃 구성 중간 커밋

static/css/navbar.css
- navbar 스크롤 오류 수정
- Update : static/navbar.css
-
=> HH-82 #comment feat : navbar 스크롤 오류 수정

posts/forms.py
- group/create 오류 및 navbar 수정
- group/create 오류 및 navbar 수정
-
=> HH-86 #comment fix : group/create 오류 및 navbar 수정

posts/forms.py, posts/templates/posts/group_create.html, posts/templates/posts/group_update.html, posts/templates/posts/post_create.html, posts/templates/posts/post_update.html
- post와 group 각각 create와 update 완성했습니다.
- Update : posts/forms.py
- Update : post/create,update, group/create,update
-
=> HH-80 HH-89 #comment feat : create, update 완성

posts/fixtures/group.json, posts/fixtures/groupcomment.json, posts/fixtures/groupimage.json, posts/fixtures/post.json, posts/fixtures/postcomment.json, posts/fixtures/postimage.json, posts/fixtures/users.json
- fixtures 초기 데이터
- posts/fixtures 7개의 json 파일
- python manage.py loaddata group.json groupcomment.json groupimage.json post.json postcomment.json postimage.json user.json
=> HH-91 #comment feat : fixtures 초기 데이터

static/css/banner.css, static/css/navbar.css, static/css/subdivision.css, templates/banner.html, templates/subdivision.html
-subdivision , banner
- update : subdivision css 수정
-  add : banner.html, banner.css
-
=> HH-92 #comment feat : subdivision css 수정

accounts/templates/accounts/profile.html
-profile.html 수정
- 팔로우, 팔로잉 리스트 모달 내용이 반영이 안되어 수정
-
=> HH-?? #fix profile.html 수정

posts/views.py
- 머지 병합 하는 과정에서 import 코드가 누락되어 발생한 에러입니다.
=> views.py 에러 해결

posts/templates/posts/group_create.html, posts/templates/posts/group_detail.html, posts/templates/posts/group_update.html, posts/templates/posts/post_create.html, posts/templates/posts/post_detail.html, posts/templates/posts/post_update.html
- create, update, delete modal 추가
- group create, update, delete modal 추가
- post create, update, delete modal 추가
-
=> HH-101 #comment feat : create, update, delete modal 추가

posts/templates/posts/group_list.html, static/css/card.css
- group_list 레이아웃 작성
- Update : posts/group_list.html 레이아웃 수정
- Update : static/css/card.css 수정
-
=> HH-97 #comment feat : group_list 레이아웃 작성

posts/templates/posts/index.html, static/css/index.css
- style : index card image 수정
- Update : posts/templates/posts/index.html
- Update : static/css/index.css
-
=> HH-103 #comment style : index card image 수정

posts/templates/posts/where.html
- where.html 배치 수정
- where.html 드롭다운과 지도 배치, 크기 수정
-
=> HH-106 #comment feat : where.html 배치 수정

posts/templates/posts/index.html, static/css/banner.css, static/css/carousel.css, static/css/index.css, templates/banner.html, templates/navbar.html
- index, carousel
- update :  index.html, index.css,carousel.css
-
=> HH-110 #comment feat : carousel 완성하기

posts/templates/posts/where.html
- where.html 인포윈도우 수정
- 인포윈도우 멘트 수정
-
=> HH-112 #comment feat : where.html 인포윈도우 수정

posts/templates/posts/index.html
- fix : 버그 수정
- Update : posts/templates/posts/index.html
-
=> HH-?? #comment fix : 버그 수정

posts/templates/posts/index.html, static/css/index.css, static/js/index_more_button.js
- 인덱스 전체취미 CSS 수정
- Update : posts/index.html 클래스 추가 및 위치 변경
- Update : static/css/index.css 카드 이미지 크기 수정
- Update : static/js/index_more_button.js querySelector 클래스 변경
-
=> HH-105 #comment refact : 인덱스 전체취미 CSS 수정

posts/templates/posts/category2.html, posts/views.py, static/css/category.css
=> HH-?? fix 카테고리 필터

posts/templates/posts/group_detail.html, posts/templates/posts/post_detail.html, static/css/carousel.css, static/css/group_detail.css
- detail 페이지 수정
- 버튼 및 레이아웃 수정, 케로젤 출력 오류 해결
-
=> HH-113 #comment refact : detail 페이지 수정

posts/templates/posts/group_detail.html, posts/templates/posts/group_list.html, posts/templates/posts/index.html, posts/templates/posts/post_detail.html, static/css/card.css, static/css/group_detail.css, static/css/group_list.css, static/css/index.css
- index, detail 등 추가 수정
- index, detail, group_list
- static/css
-
=> HH-119 index, detail 등 추가 수정

posts/templates/posts/category2.html, static/css/category.css
- 스타일 정리
-링크 부분에 마우스오버하면 파란색으로 바뀌던 것 수정됨
-큰 폭으로 봤을 때 카드 4장 보이도록 수정
-근데 모바일 사이즈로 줄였을 때는 하나씩 밖에 안 보임.. 카드 크기를 조절하지 않으면 여백과 맞지 않아서 아래줄로 내려감
-
=> HH-108 # style : category.html

posts/templates/posts/index.html
=> index border 삭제

posts/forms.py, posts/views.py
- 최종 오류 수정 완료
- group_update 하면 기존의 사진 파일들이 누적돼서 생성되던 것 사진 파일 초기화 시켜서 누적 안되게끔 수정 완료
- group_create 처음에 forms.py 건드려서 하려다가 views.py 수정 후 정상 작동 확인
-
=> HH-122 #comment fix : 최종 오류 수정 완료

accounts/templates/accounts/profile.html
- profile 게시글 갯수 조절
- Update : profile.html
-
=> HH-123 #comment refact : profile 게시글 갯수 조절

templates/base.html, templates/footer.html
- footer 수정
- templates/base, footer.html
모바일 반응형으로 레이아웃 수정
-
=> HH-124 #comment refact : footer 수정

templates/base.html
- base  아이콘 바꾸기
- Hobby 로고 아이콘 변경
-
=> HH-125 #comment refact : base  아이콘 바꾸기

posts/templates/posts/where.html
- Where 템플릿 필터링 오류 수정
Update : posts/templates/posts/where.html 옵션 밸류 값 수정
-
=> HH-128 #comment fix : Where 템플릿 필터링 오류 수정

posts/templates/posts/group_list.html, templates/subdivision_g.html
-아이콘 필터 적용
-서브디비전2 만들어서 그룹 필터링되도록 수정
-변수 써서 해보려고 했는데 시간 없어서 냅다 하드코딩
-group_list.html은 include 파일명 변경 외에 변경사항 없음
-
=> HH-?? style : 그룹리스트 아이콘 필터 적용
